name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: main

jobs:
  linux:
    name: ${{ matrix.CONDA_ENV }}-pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONDA_ENV: [py39, py310, py311, py312]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment-${{ matrix.CONDA_ENV }}.yml

      - name: pip-install
        shell: bash -l {0}
        run: |
          pip install -e . --no-deps

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --verbose --cov=uavro

  win:
    name: win
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ci/environment-py310win.yml

      - name: pip-install
        shell: bash -l {0}
        run: |
          pip install -e . --no-deps

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --verbose --cov=uavro
